API to get master nodes for mesos and aurora
aurora-scheduler/australis pull request #38
Opened 2022-08-19 23:41 UTC by lawwong1

**Description:**
2 new APIs to fetch aurora master nodes and mesos master nodes

**Usage:**
1. Fetch aurora master nodes:
for example:  
$ ./australis fetch master 10.180.52.93 10.180.52.175 --toJSON
INFO[0000] Fetching master nodes from [10.180.52.93 10.180.52.175]  
{"leader":"gpzkmmas2-4.gpf-prod.us-central1.gcp.dev.paypalinc.com","masterNodes":"gpzkmmas2-5.gpf-prod.us-central1.gcp.dev.paypalinc.com,gpzkmmas2-6.gpf-prod.us-central1.gcp.dev.paypalinc.com,gpzkmmas2-4.gpf-prod.us-central1.gcp.dev.paypalinc.com"}

2. Fetch mesos master nodes:
for example:   
$ ./australis fetch mesos master 10.180.52.93 10.180.52.175
INFO[0000] Fetching Mesos-master nodes from Zookeeper node(s): [10.180.52.93 10.180.52.175]  
{"leader":"gpzkmmas2-5.gpf-prod.us-central1.gcp.dev.paypalinc.com","masterNodes":"gpzkmmas2-5.gpf-prod.us-central1.gcp.dev.paypalinc.com,gpzkmmas2-6.gpf-prod.us-central1.gcp.dev.paypalinc.com,gpzkmmas2-4.gpf-prod.us-central1.gcp.dev.paypalinc.com"}

**Notes:**
This PR depends on another PR on gorealis: https://github.com/aurora-scheduler/gorealis/pull/20

2022-08-22 16:57 UTC, lenhattan86 requested changes

2022-08-22 16:57 UTC, lenhattan86 commented on cmd/fetch.go
> +			fmt.Println(mesosAgentFlags.Master)
the function stops here and does not return all the master nodes.

2022-08-22 17:40 UTC, lawwong1 commented on cmd/fetch.go
> +	masterCmd.Flags().String("zkPath", "/aurora/scheduler", "Zookeeper node path to get master nodes/leaders")
Would change

2022-08-24 15:55 UTC, lenhattan86 commented
@lawwong1  please point gorealis to the version https://github.com/aurora-scheduler/gorealis/releases/tag/v2.29.0

2022-08-24 17:24 UTC, lawwong1 commented
Done

2022-08-24 17:25 UTC, merged